from . import res_partner
from . import res_partner_bank
from . import res_partner_form
from . import ss_erp_partner_payment_term
from . import ss_erp_contact_category
from . import ss_erp_partner_construction
from . import ss_erp_partner_performance
from . import ss_erp_delivery_pattern
from . import ss_erp_delivery_vehicle