# -*- coding: utf-8 -*-

from . import bis_category
from . import mail_mail
from . import model
from . import organization
from . import organization_category
from . import partner_rebate
from . import product_template
from . import purchase_order_line
from . import res_company
from . import ss_erp_contact_category
from . import ss_erp_partner_construction
from . import ss_erp_partner_performance
from . import res_partner
from . import res_users
from . import purchase_order
from . import responsible_department
from . import stock_picking
from . import res_partner_bank
from . import ss_erp_multi_approvers
from . import res_partner_form
from . import approval_category
from . import approval_lost
from . import approval_request
from . import hr_employee
from . import sale_order
from . import ss_erp_account_subaccount
from . import account_account
from . import stock_scrap
from . import ss_erp_partner_payment_term
